language: r
cache: packages

before_install:
  # Specify package folder
  - cd griph
  # Make sure default environment variable do not interfere with MPI:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX


install:
  #- Rscript -e 'devtools::install_deps("./")'
  - Rscript -e 'install.packages(c("devtools","roxygen2","knitr"));'

#script:
#  - Rscript -e 'devtools::check("./")'
#  - Rscript -e 'source("https://bioconductor.org/biocLite.R")'
#  - Rscript -e 'biocLite()'
#  - Rscript -e 'biocLite(c("BiocStyle"))'

#Build on both linux and OSX:
os:
  - linux
  - osx

compiler:
  - clang
  #- gcc

#Allow for failure in osx build:
matrix:
  allow_failures:
    - os: osx

#after_success:
#  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change