language: r
cache: packages

sudo: required

script:
#  - Rscript -e 'devtools::check("./")'
  - Rscript -e 'source("https://bioconductor.org/biocLite.R")'
  - Rscript -e 'BiocInstaller::biocLite(c("BiocStyle"))'


matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    before_install: |1
     cd griph
     mkdir ~/.R
     cat <<EOF > ~/.R/Makevars
     CC=gcc-6
     CXX=g++-6
     CXX1X=g++-6
     CXX11=g++-6
  - os: osx
    r: release
    before_install: |1
     cd griph
  - os: linux
    dist: trusty
    r: devel
    before_install: |1
     cd griph
     mkdir ~/.R
     cat <<EOF > ~/.R/Makevars
     CC=gcc-6
     CXX=g++-6
     CXX1X=g++-6
     CXX11=g++-6
  - os: osx
    r: devel
    before_install: |1
     cd griph
    env: _R_CHECK_FORCE_SUGGESTS_=FALSE
  allow_failure:
    r: devel
    r_check_args: --use-valgrind

env:
  global:
  - OS=$(uname -s)

cran: http://cran.rstudio.com

r_packages:
  - covr
  - BH
  - ggplot2

r_binary_packages:
  - testthat
  - png
  - Rcpp
  - RcppArmadillo
  - RcppProgress
  - dbscan
  - knitr
  - rmarkdown
  - roxygen2
  - devtools

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - gfortran-6
      - libudunits2-dev
  brew_packages:
      - udunits


#after_success:
#  - Rscript -e 'covr::coveralls()'
#after_success:
#- if [[ "$TRAVIS_R_VERSION" != "devel" && ("$TRAVIS_OS_NAME" == "osx") ]]; then R CMD INSTALL --build $PKG_TARBALL; fi
after_success:
- R CMD INSTALL --build $PKG_TARBALL; fi


#before_deploy:
#  - export FILE_TO_UPLOAD=$(ls ${TRAVIS_BUILD_DIR}/*/*.tar.gz)
#  - export FILE_TO_UPLOAD=$(ls ${TRAVIS_BUILD_DIR}/*/*.tar.gz)
#  - export FILE_TO_UPLOAD=$(ls _builds/*/*.tar.gz)

deploy:
  provider: releases
  api_key:
      secure: INOd7zxJYw6WRqFOZO7EhrR6zoWmR5apThTndG+D4FkM/OgF35cyVyyqYKCy78d0RO49eF9wUYvCr1MsxrMF1tyj87apb6ddOJPMrAfxsM7GOpmjskuvmoOsKBOlu9oDrEO9n0rDJRYpkweqBKVU8z1t4DUV8NKptERkEBpbhbdvpOb9mGDt6/kUjLf+ea+1SSig/LmLHgBygcMpu/1Qidw/yVISsU6idxA0mcnu75H27OFSFu+A0p2dLYyzz4eQ3v6b4GsHcq9F/2ixQmp3zwUfwv18tiauOXQEonzTf7bz6XieSOFJPRPCtZmePaM2Sz5qCwY0AxyqkQMLr/jTjiZQBAeFpgQkx8zSf51iccrcJHDcEipXhhkpDKO1UgdlmA/9bb9XXsjF032T9MprboaESTxpKSykp5pne+cXJjuEZwV1AWfDYF0W8ShKw02K5lG6YSjiJmvYyN0+xQqz1NsxCpXs7LKvUfE1muO1vgPmoIiYfn5AEwcR3/1NorD/EpM3p6w3UvO1cIhMn2vR0SIw542E5oovDkunCsw+CDPeRcGADBrlxAiGQd1s24s+r/OwapnAt6rohOlTsVFcYjBeelWaDhl8/yuVwcxsKRIn2iPtUw0UArzy49KVsRurOo6SdSggu+hJmeGFVzj64eXyXgAPogVnuRLgGBISgs0=
  file_glob: true
  #file: "${FILE_TO_UPLOAD}"
  file: griph_*.t*gz
  skip_cleanup: true
  on:
    tags: true
 #   condition: "$r = release"
 #   r: release

cran: http://cran.rstudio.com


notifications:
  email:
    on_success: change
    on_failure: change