language: r
cache: packages

sudo: required

before_install:
  # Make sure default environment variables do not interfere with MPI:
  #- test -n $CC  && unset CC
  #- test -n $CXX && unset CXX

install:
  # Install package building R dependencies:
  #- Rscript -e 'install.packages(c("devtools"));'
  #- Rscript -e 'devtools::install_deps("./")'

script:
#  - Rscript -e 'devtools::check("./")'
#  - Rscript -e 'source("https://bioconductor.org/biocLite.R")'
#  - Rscript -e 'biocLite()'
#  - Rscript -e 'biocLite(c("BiocStyle"))'


matrix:
  include:
  - os: linux
    dist: trusty
    r: release
    before_install: |1
     cd griph
     mkdir ~/.R
     cat <<EOF > ~/.R/Makevars
     CC=gcc-6
     CXX=g++-6
     CXX1X=g++-6
     CXX11=g++-6
  - os: osx
    r: release
    before_install: |1
     cd griph
  - os: linux
    dist: trusty
    r: devel
    before_install: |1
     cd griph
     mkdir ~/.R
     cat <<EOF > ~/.R/Makevars
     CC=gcc-6
     CXX=g++-6
     CXX1X=g++-6
     CXX11=g++-6
  - os: osx
    r: devel
    before_install: |1
     cd griph
    env: _R_CHECK_FORCE_SUGGESTS_=FALSE
  allow_failure:
    r: devel
    r_check_args: --use-valgrind

env:
  global:
  - OS=$(uname -s)

cran: http://cran.rstudio.com

r_packages:
  - covr
  - BH
  - ggplot2

r_binary_packages:
  - testthat
  - png
  - Rcpp
  - RcppArmadillo
  - RcppProgress
  - dbscan
  - knitr
  - rmarkdown
  - roxygen2
  - devtools

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - gfortran-6
      - libudunits2-dev
  brew_packages:
      - udunits



#Allow for failure in osx build:
#matrix:
#  allow_failures:
#    - os: osx

#after_success:
#  - Rscript -e 'covr::coveralls()'


#before_deploy:
#  - export FILE_TO_UPLOAD=$(ls _builds/*/Foo-*.tar.gz)

#deploy:
#  provider: releases
##  user: "GITHUB USERNAME"
##  password: "GITHUB PASSWORD"
   api_key: "bcdf070564c2112120b99ac76ab9e097e01bb599"
#  file: "${FILE_TO_UPLOAD}"
#  skip_cleanup: true
#  on:
#    tags: true


notifications:
  email:
    on_success: change
    on_failure: change