# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: |
        Bootstrap
# Adapt as necessary starting from here
branches:
  only:
    - master

before_build:
   ps: |
        cp ..\travis-tool.sh .\travis-tool.sh
        cp ..\travis-tool.sh griph\travis-tool.sh
        cp travis-tool.sh.cmd griph\travis-tools.sh.cmd
        cd griph
        bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"
  #- ps: ...

build_script:
  - travis-tool.sh install_deps

after_build:
  - ps: R CMD INSTALL --build griph

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

deploy:
  - provider: releases
    name: Bits
    auth_token:
      secure: byrMk4PZnSieDDIT01xfa86wYfX/7b0Hfs4XZPrLH9gpIv+EtVYPLEzqpvV0w1BR
    artifact: /.*\.zip
    on:
    ##  appveyor_repo_tag: true
      branch: master