# DO NOT CHANGE the "init" and "install" sections below
# Download script file from GitHub

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: |
        Bootstrap
        
        
# Adapt as necessary starting from here


environment:
  global:
    WARNINGS_ARE_ERRORS: 0


matrix:
  - R_VERSION: release
    R_ARCH: x64
    GCC_PATH: mingw_64



branches:
  only:
    - master

before_build:
   ps: |
        cp ..\travis-tool.sh .\travis-tool.sh
        cp ..\travis-tool.sh griph\travis-tool.sh
        cp travis-tool.sh.cmd griph\travis-tools.sh.cmd
        cd griph
        bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"
  #- ps: ...

build_script:
  - travis-tool.sh install_r devtools
  - travis-tool.sh install_r roxygen2
  - travis-tool.sh install_r knitr
  - travis-tool.sh install_r rmarkdown
  - travis-tool.sh install_r Rcpp
  - travis-tool.sh install_r RcppArmadillo
  - travis-tool.sh install_r RcppProgress
  - travis-tool.sh install_r covr
  - travis-tool.sh install_r BH
  - travis-tool.sh install_r ggplot2
  - travis-tool.sh install_bioc_ BiocStyle
  - travis-tool.sh install_deps

  #- R CMD INSTALL --build griph

#The run_tests also builds binaries on the windows platform:
test_script:
  - cd griph
  - travis-tool.sh run_tests
  - travis-tool.sh run_tests > test.out
  - ls -l >> test.out
  - cd ..
  - ls -l >> test.out

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '**\*.out'
    name: tout

  - path: '\*_*.tar.gz'
    name: tar

  - path: 'griph*.zip'
    name: zip

cache:
  - C:\RLibrary

#deploy:
#  - provider: GitHub
#    auth_token:
#      secure: byrMk4PZnSieDDIT01xfa86wYfX/7b0Hfs4XZPrLH9gpIv+EtVYPLEzqpvV0w1BR
#    artifact: /griph*.zip/
#    on:
#    ##  appveyor_repo_tag: true
#      branch: master
